{application, ewrepo,
 [{description, "Erlang repository interface"},
  {vsn, "0.16.2.2"},
  {modules, [ewr_fetch,
             ewr_depends,
             ewr_deps_engine,   
             ewr_resolver,
             ewr_put,
             ewr_repo_paths,
             ewr_repo_dav,
             ewr_util]},
  {registered, []},
  {versioned_dependencies, [{ibrowse, "1.2.4.1", gte}]},
  {applications, [kernel, stdlib, ibrowse, ewlib]}]}.
